# Generated by Django 3.0.2 on 2020-11-15 09:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20201115_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='producedby',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, verbose_name='出版社'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='purchaseDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='購入日'),
        ),
    ]
