# Generated by Django 3.0.2 on 2020-11-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20201115_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='purchaseDate',
            field=models.DateTimeField(verbose_name='購入日'),
        ),
    ]
