# Generated by Django 3.0.2 on 2020-11-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20201115_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='purchaseDate',
            field=models.CharField(max_length=30, verbose_name='購入日'),
        ),
    ]
