# Generated by Django 3.0.2 on 2020-11-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20201115_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='createdAt',
            field=models.DateField(auto_now_add=True, verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='book',
            name='deadline',
            field=models.DateField(auto_now_add=True, verbose_name='貸出期限'),
        ),
        migrations.AlterField(
            model_name='book',
            name='updatedAt',
            field=models.DateField(auto_now_add=True, verbose_name='更新日時'),
        ),
    ]
