# Generated by Django 3.0.2 on 2020-11-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20201115_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='本番号'),
        ),
    ]
