# Generated by Django 3.0.2 on 2020-11-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20201115_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('Loginid', models.CharField(max_length=10, verbose_name='ログインID')),
                ('password', models.CharField(max_length=10, verbose_name='パスワード')),
                ('mail', models.CharField(max_length=30, verbose_name='メールアドレス')),
            ],
        ),
    ]
